sudo: required
dist: bionic
language: node_js
node_js:
- '10'
addons:
  apt:
    packages:
    - xvfb
    - gnome-keyring
    - libgnome-keyring-dev
    - node-gyp
    - icnsutils
    - graphicsmagick
    - xz-utils
    - rpm
    - libarchive-tools
os:
- linux
- osx
- windows
cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - ~/AppData/Local/electron/Cache/
  - ~/Library/Caches/electron/
  - npm
  - yarn
script:
- echo Building MavensMate Desktop ...
- "./bin/travis-build.sh"
env:
  global:
  - YARN_GPG=no
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+(\\-(alpha|beta)\\.\\d+$|$)/"
