sudo: required
dist: bionic
language: node_js
node_js:
- '10'
addons:
  apt:
    packages:
    - xvfb
    - gnome-keyring
    - libgnome-keyring-dev
    - node-gyp
    - icnsutils
    - graphicsmagick
    - xz-utils
    - rpm
os:
- linux
- osx
- windows
cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
script:
- echo Building MavensMate Desktop ...
- "./bin/travis-build.sh"
env:
  global:
  - secure: fQQgdB/MGLRMwZr95KmJNfZsBx5fgoA1gS1DgQCLjWaHzvsLYvPV9RA78kQFn0Q6a4L+tV1VPZErYV4w1UArBPMub8XkG/lmCYCaEwhI1huGDjFCBUxv7jgsMi/XJB7vRtAuNQrzJqQW6/yEyCmB8YlHqEwxTD+34A4Uv85ivdtmxQijR6fQSj+jzZtb13eIPofEcDhfUoTocFy6E9RIZn0SR3J6GdNmhom9+NQlEI/9VcwPW7mw7riR9Ka43UqzdVbNVCQFhwF3rF8PuDIp8B35xTfukHwcLOYXAiu0FFdJjy1ozz8vYbsAHJ0EuM8t0EDu0OrlXqXH9wYKI4u1tcoiQGoblIJNxo0jhLNMs37fRgy2pD1x0Tc3cio4gZHsqEBS/6UxBEtS9hYuIf9KKpGa/ToYoRgNmuJHpbdlAWJb+d8pF+ZAAuuRcB64Ti9agzvXEbNz9fH3q4j01NtYOiT45hSdgSzxRbJ38rsVPvwObjiY24zxSfss+soOqEbqJR0zPT1GIje5MEcFHmXludcSjfPyj0yXEN4MJYMWeV5qNN/32VYIb2rq2aWew7KyIPqf75UFBqwd7g0poG+1S/R1PAT+/7gJvfd5B0etsrj6FaZQPqS37DhBAGCqaZdI6GY43SX5vKbtXx5KindC20qrhX2O8FU4pf2i2AY7A/4=
  - secure: tZUGOgeloS41gkLjJn7wj6DxyFPIkCVCjpv5MAbandMe9QBQzs0CENCMwnqzcx4zA46EDEPVx2fCsGHCR0/SUNxzzk/wsRdOTgA76/2G8ThEheQ6sC6he2/s1VFqySP4DBq45DAp0FGg/QaMNKzZCrz/Kq34t7jyh8VIhVObwHEuuGkqm4+W0Wa0vg3yxn54ptG2ysVbdi+fbf+MyVA2YzwQJq4s2Idmx/ZjcFJvM/Jte+NSyO5w/c+GumKcyHtkhxe8JINVsn7n46HKe3puwXw2H7O9yFKBZYyd1xWXeS3eHlnHmlgRwZwjE9TywwhDKI3gmlAizhF43xvNQKZ+r2f4Xk5X1VeC9HohV30G/xUTuOdZQ6atOSy5uN8dmXNmXBjH5TCeKjptb3SyRecc0ky1onhB8RK8nm47HYCpZ8MVTqX8HsstCz2OpkQ9hAQadMB5lOf7QhNwIztsu4AZZpvsRg6tP8y0kd//ZZlHyNT0p5n0x9S0TG25Zwj+Q/3eX9mRMlolxmW6P5ShAY8VdZ9FUu7ijcpFlPiZGSLiUtbUmKvnzpvy65ydvckUovCg1Ox1iAfOdDAWm97zavwUeO6j+CPmI0ctjwprxv4IUJqwBF5yUZzVBEJSYBR/hdxwTqCsirU4S1iZXsgjgLmFkVYrXt5g+KoyPMcbPmyDVVg=
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+(\\-(alpha|beta)\\.\\d+$|$)/"
deploy:
  provider: releases
  api_key:
    secure: ibuoKFOl9PiLLtXOYy8PEWzIK5OPfEhZAptU/uWXjHb/pZ7W8IAwurB2mX/nVOLbmm6prYYjGBTCivzKeUTMhCBfO2dwrjeyL7l6WprCoXGHB8dhseb7j996zpDfCVFc2HzJK3/ShS9sTeVaY+ifmfOoanGgC2dn7CqDML5YeDAeKB51Wppqn4ZfPYaZ0hoGPU+7nd5R1MDO82bIRpPw5bLHvZfZ4ncTFn5u8vmxBN30RrHF3ceA9LoAuwWudD9804jLipzACzEarQIYhIbauIOdc2vpm5uOnH1URhl9GFKVoU9r4RrWPiEwH72t2xmfZDSZ9Ymql2xEsnMZJz2+3heN/IHN0DRzTBlt7h8za4L2HJ8S1s/0zTV8Yfxxwsln7vGmKDT9HXMSUY4DkFIyxkKeYGOG8vjKl1uGS5S2L+rHwKOHEle4xO65yfcYAsouYt0Kru7PD3VD+3C5tPA3RjSNDnZvZVKugH6dRhu1fnrCOcS5lHbZL9n3g2RlZL7WP/zz7GLI5SVHSFqp/Qze7T6prNz48p8fQzcMD0KMwfV61aZIwDea1f2j4YwjR0DO48GpK3ofbln9r7mPgU2WOPN61ngW5srDOHAhg0UCPF+dxjw2dbRN/cYpCiDiffP/fF4d6CXWOeUpenQ4YK4RyqcPNfVYqoPdkTvECs8+ND8=
  file: dist/MavensMate-Desktop*
  on:
    tags: true
